"""The client-facing documents must render from assets this repo actually ships.

WHY THIS EXISTS: on 2026-09-02, in the practice-check repo, four hand-written
documents carried "file:///C:/Users/John Anastacio/..." in their <head> --
fonts and stylesheets living in two OTHER projects on one machine. They rendered
perfectly there and would render as unstyled fallback text anywhere else. The
test meant to prevent it only ever looked at the GENERATED report, so the four
hand-written files went unchecked for weeks.

These cover ALL FOUR documents from the start, and check the HTML as TEXT.
Rendering is not a check here: it passes on the author's machine whatever the
paths say, which is precisely why the original defect survived.

Generated by docs/make_asset_test.py -- edit there, not here.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
ASSETS = REPO / "assets"

DOCUMENTS = [
    "demo/decision_card.html",
    "demo/handover.html",
    "deck/askall-deck.html",
    "deck/askall-carousel.html",
]

FONTS = [
    "Inter-Regular.ttf", "Inter-Medium.ttf", "Inter-SemiBold.ttf",
    "Inter-Bold.ttf", "Inter-ExtraBold.ttf",
    "JetBrainsMono-Regular.ttf", "JetBrainsMono-Medium.ttf",
]


def _tracked_files() -> set[str]:
    """Everything git actually has, as repo-relative posix paths.

    "Is it on disk" is the wrong question -- a gitignored font passes every
    other check and still breaks a fresh clone.
    """
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    )
    return set(out.stdout.split())


@pytest.mark.parametrize("name", DOCUMENTS)
def test_the_document_ships_in_the_repo(name):
    """A document a clone does not receive cannot be rendered by anyone else."""
    assert (REPO / name).is_file(), f"{name} is missing"
    assert name in _tracked_files(), f"{name} is not tracked by git"


@pytest.mark.parametrize("name", DOCUMENTS)
def test_the_document_uses_no_machine_specific_path(name):
    """No absolute file:// URL, and none of the known off-repo asset homes."""
    html = (REPO / name).read_text(encoding="utf-8")
    assert "file:///" not in html, f"{name} carries an absolute file:// URL"
    for elsewhere in ("scratch/resume-fit", "scratch/sales-playbook", "scratch/practice-check"):
        assert elsewhere not in html, f"{name} points at {elsewhere}"


@pytest.mark.parametrize("name", DOCUMENTS)
def test_every_asset_the_document_references_is_tracked(name):
    """Each ../assets/... reference must resolve to a file git actually has."""
    doc = REPO / name
    html = doc.read_text(encoding="utf-8")
    refs = set(re.findall(r"(\.\./assets/[A-Za-z0-9_./-]+?\.(?:ttf|css))", html))
    assert refs, f"{name} references no repo assets -- did the paths change shape?"
    for ref in refs:
        resolved = (doc.parent / ref).resolve()
        assert resolved.is_file(), f"{name} -> {ref} does not exist"
        rel = resolved.relative_to(REPO).as_posix()
        assert rel in _tracked_files(), f"{name} -> {ref} is not tracked by git"


@pytest.mark.parametrize("name", FONTS)
def test_every_font_weight_ships(name):
    """Without per-weight faces Chromium synthesises them and spacing goes uneven."""
    assert (ASSETS / "fonts" / name).is_file(), f"{name} missing from assets/fonts"
    assert f"assets/fonts/{name}" in _tracked_files(), f"{name} is not tracked by git"


@pytest.mark.parametrize("name", ["brand.css", "components.css", "brand-light.css"])
def test_every_stylesheet_ships(name):
    assert (ASSETS / "pdf" / name).is_file(), f"{name} missing from assets/pdf"
    assert f"assets/pdf/{name}" in _tracked_files(), f"{name} is not tracked by git"


def test_the_font_licences_ship_alongside_the_fonts():
    """Inter and JetBrains Mono are OFL: redistributing them carries the licence."""
    for licence in ("OFL-Inter.txt", "OFL-JetBrainsMono.txt"):
        assert (ASSETS / "fonts" / licence).is_file()
        assert f"assets/fonts/{licence}" in _tracked_files()
